// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"IdentifyService/internal/app/system/dao/internal"
	"IdentifyService/internal/app/system/model/entity"
	"context"
	"database/sql"
	"fmt"

	"github.com/gogf/gf/v2/database/gdb"
)

// internalSysDeptDao is internal type for wrapping internal DAO implements.
type internalSysDeptDao = *internal.SysDeptDao

// sysDeptDao is the data access object for table sys_dept.
// You can define custom methods on it to extend its functionality as you wish.
type sysDeptDao struct {
	internalSysDeptDao
}

var (
	// SysDept is globally public accessible object for table sys_dept operations.
	SysDept = sysDeptDao{
		internal.NewSysDeptDao(),
	}
)

// Fill with you ideas below.
func (d *sysDeptDao) Insert(ctx context.Context, tx gdb.TX, data map[string]interface{}) (deptID int64, err error) {
	deptID, err = d.internalSysDeptDao.Ctx(ctx).TX(tx).Data(data).InsertAndGetId()
	if err != nil {
		return 0, err
	}
	return deptID, nil
}

func (d *sysDeptDao) Get(ctx context.Context, deptID uint64) (out *entity.SysDept, err error) {
	out = &entity.SysDept{}
	err = d.internalSysDeptDao.Ctx(ctx).Where(d.Columns().DeptId, deptID).Scan(out)
	if err != nil {
		if err == sql.ErrNoRows {
			return nil, fmt.Errorf("部门不存在")
		}
		return nil, err
	}
	return out, nil
}
