// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"

	"github.com/tiger1103/gfast/v3/internal/app/common/model"
	"github.com/wenlng/go-captcha/captcha"
)

type ICaptcha interface {
	GetVerifyImgString(ctx context.Context) (idKeyC string, base64stringC string, err error)
	VerifyString(id, answer string) bool
	GetCaptchaV2(ctx context.Context) (dots map[int]captcha.CharDot, img, thumb, key string, err error)
	CheckCaptchaV2(ctx context.Context, key string, dots string, removeKey ...bool) (err error)

	SendSmsCode(ctx context.Context, phone string, bussinessType model.SMSBusinessType) (err error)
	ValidateSmsCode(ctx context.Context, phone string, bussinessType model.SMSBusinessType, code string) (err error)
}

var localCaptcha ICaptcha

func Captcha() ICaptcha {
	if localCaptcha == nil {
		panic("implement not found for interface ICaptcha, forgot register?")
	}
	return localCaptcha
}

func RegisterCaptcha(i ICaptcha) {
	localCaptcha = i
}
